---
providers:
  kubernetesCRD:
    namespaces:
      - default
      - traefik
  kubernetesIngress:
    namespaces:
      - default
      - traefik

ports:
  traefik:
    expose: true
    nodePort: 32090
  web:
    nodePort: 32080
  websecure:
    nodePort: 32443
    
additionalArguments:
  - --entrypoints.web.http.redirections.entryPoint.to=websecure
  - --entrypoints.web.http.redirections.entryPoint.scheme=https
  # Update the email below
  - --certificatesresolvers.myresolver.acme.email=email@example.com
  - --certificatesresolvers.myresolver.acme.storage=/data/acme.json
  - --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
  - --certificatesresolvers.myresolver.acme.preferredchain="ISRG Root X1"
  - --certificatesresolvers.myresolver.acme.keytype=RSA4096
  - --certificatesresolvers.myresolver.acme.httpchallenge=true
  - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
  - --certificatesresolvers.myresolver.acme.dnschallenge.provider=desec
  - --certificatesresolvers.myresolver.acme.dnschallenge.delaybeforecheck=0
  - --certificatesresolvers.myresolver.acme.dnschallenge=true
  - --certificatesresolvers.myresolver.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53


env: 
  - name: DESEC_TOKEN
    value: "Update this with token from desec dns"

service:
  type: NodePort
